In [1]:
import numpy as np
# Sistema:
A = np.array([[3, 2, 4],
              [1, 1, 2],
              [4, 3,-2]])

b = np.array([1,2,3])

# Eliminação de Gauss
def gauss_elimination(A, b):
    
  n = A.shape[0]

  At = np.zeros([n,n+1])
  At[:,:n] = A
  At[:,n:] = b.reshape(n,1)
  
  # Etapas : k
  for k in range(n):

    # Linhas : i
    for i in range(k+1, n):
      m = At[i,k] / At[k,k] #multiplicador
      At[i,:] = At[i,:] - m * At[k,:]

  return At


# Solução do sistema triangular
def solve_triangular(At):
    
  n = At.shape[0]
  x = np.zeros(n)
  nt = n-1




  x[nt] = At[nt,n] / At[nt,nt]


  for i in range(nt-1,-1,-1):
    x[i] = At[i,n]

    for j in range(i+1,n):
      x[i] = x[i] - At[i,j]*x[j]

    x[i] = x[i] / At[i,i]

  return x


np.set_printoptions(precision=2, suppress=True)
print('Matriz aumentada [[A] | [b]]')
print(np.concatenate((A,b.reshape(len(b),1)), axis=1))

At = gauss_elimination(A,b)
print('\n Sistema triangular equivalente:')
print(At)

x = solve_triangular(At)

print('\n Solução:')
print(f'[x] = {x}')

Matriz aumentada [[A] | [b]]
[[ 3  2  4  1]
 [ 1  1  2  2]
 [ 4  3 -2  3]]

 Sistema triangular equivalente:
[[ 3.    2.    4.    1.  ]
 [ 0.    0.33  0.67  1.67]
 [ 0.    0.   -8.   -0.  ]]

 Solução:
[x] = [-3.  5.  0.]
